-- Enable UUID generation
create extension if not exists "pgcrypto";

-- users: stores Google OAuth credentials and Slack identity
create table users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  google_id text unique not null,
  slack_user_id text,
  access_token text,
  refresh_token text,
  token_expiry timestamptz,
  digest_time text default '09:00',
  created_at timestamptz default now()
);

-- meetings: synced from Google Calendar, with classification results
create table meetings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  google_event_id text not null,
  title text,
  description text,
  start_time timestamptz,
  duration int,
  attendee_count int,
  is_organiser bool default false,
  is_recurring bool default false,
  meet_link text,
  classification text,
  confidence int,
  reason text,
  created_at timestamptz default now(),
  unique(user_id, google_event_id)
);

-- overrides: user-initiated reclassifications
create table overrides (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid references meetings(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  original_classification text not null,
  new_classification text not null,
  overridden_at timestamptz default now()
);

-- status_updates: async check-in submissions before a meeting
create table status_updates (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid references meetings(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  completed text,
  plan text,
  blockers text,
  status_tag text,
  submitted_at timestamptz default now()
);

-- summaries: post-meeting transcript summaries generated by Claude
create table summaries (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid references meetings(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  transcript_text text,
  summary text,
  action_items text,
  created_at timestamptz default now()
);
